/*
Copyright (c) 2026

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apisv1alpha1 "github.com/lioneljouin/pizzipam/apis/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPSliceLister helps list IPSlices.
// All objects returned here must be treated as read-only.
type IPSliceLister interface {
	// List lists all IPSlices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1alpha1.IPSlice, err error)
	// Get retrieves the IPSlice from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisv1alpha1.IPSlice, error)
	IPSliceListerExpansion
}

// iPSliceLister implements the IPSliceLister interface.
type iPSliceLister struct {
	listers.ResourceIndexer[*apisv1alpha1.IPSlice]
}

// NewIPSliceLister returns a new IPSliceLister.
func NewIPSliceLister(indexer cache.Indexer) IPSliceLister {
	return &iPSliceLister{listers.New[*apisv1alpha1.IPSlice](indexer, apisv1alpha1.Resource("ipslice"))}
}
