# This slice owns 192.168.0.0/26  (usable .1 - .62)
# networkAddress = int(192.168.0.0) = 3232235520
# Compute with:  ./scripts/ip2int.sh 192.168.0.0
apiVersion: multinetwork.networking.x-k8s.io/v1alpha1
kind: IPSlice
metadata:
  name: blue-network
spec:
  podNetworkRef:
    name: abc
    kind: blue-network
  baseSubnet: # 192.168.0.0/24
    networkAddress: 3232235520
    prefixLength: 24
    addressSpace: 256
  sliceSubnet: # 192.168.0.0/26
    networkAddress: 3232235520
    prefixLength: 26
    addressSpace: 64
  request:
  - name: alpha
  # - name: beta
  # - name: a
  # - name: b
  # - name: c
  # - name: d
  # - name: e
  # - name: f
  # - name: g
  # - name: h
  # - name: i
  # - name: j
  # - name: k
  # - name: l
  - name: m