---
apiVersion: multinetwork.networking.x-k8s.io/v1alpha1
kind: IPSlice
metadata:
  name: abc.blue-network.3232235520
spec:
  podNetworkRef:
    name: abc
    kind: blue-network
  sliceSubnet: # 192.168.0.0/26 (slice size is a fixed /26)
    networkAddress: 3232235520
    prefixLength: 26
    addressSpace: 64
  request:
  - name: request-0 # request an IP in the 192.168.0.4/30 subnet (good as in the 192.168.0.0/26), so an IP from 192.168.0.4 to 192.168.0.7
    networkAddress: 3232235524
    prefixLength: 30
  - name: request-1 # request an IP in the 192.168.0.4/30 subnet (good as in the 192.168.0.0/26), so an IP from 192.168.0.4 to 192.168.0.7
    networkAddress: 3232235524
    prefixLength: 30
  - name: request-2 # request an IP in the 192.168.0.0/26 subnet, so an IP from 192.168.0.0 to 192.168.0.63
  - name: request-3 # request an IP in the 192.168.0.0/26 subnet, so an IP from 192.168.0.0 to 192.168.0.63
  - name: request-4 # request an IP in the 192.168.0.64/26 subnet (bad as not in the 192.168.0.0/26), this must be rejected
    networkAddress: 3232235584
    prefixLength: 26
  - name: request-5 # request an IP in the 192.168.0.64/16 subnet (keep generating in the 192.168.0.0/26), we don't care as the prefixLength is bigger than the sliceSubnet.prefixLength, we should just check that this IPSlice subnet is a subset of this request, here it is as 192.168.0.0/26 is a subset of 192.168.0.0/24
    networkAddress: 3232235520
    prefixLength: 24
  - name: request-6 # request an IP in the 192.168.1.64/16 subnet, we should just check that this IPSlice subnet is a subset of this request, here it is not as 192.168.0.0/26 is not a subset of 192.168.1.0/24
    networkAddress: 3232235776
    prefixLength: 24